
// This file has been generated by the GUI designer. Do not modify.
namespace Proyecto
{
	public partial class Calculadora
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.VButtonBox vbuttonbox5;
		private global::Gtk.VButtonBox vbuttonbox3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VButtonBox vbuttonbox10;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button button1;
		private global::Gtk.VButtonBox vbuttonbox6;
		private global::Gtk.Button button2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VButtonBox vbuttonbox7;
		private global::Gtk.Button button4;
		private global::Gtk.VButtonBox vbuttonbox8;
		private global::Gtk.Button button5;
		private global::Gtk.VButtonBox vbuttonbox9;
		private global::Gtk.VButtonBox vbuttonbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Entry entry1;
		private global::Gtk.Entry entry2;
		private global::Gtk.VButtonBox vbuttonbox4;
		private global::Gtk.Label label1;
		private global::Gtk.VButtonBox vbuttonbox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Proyecto.Calculadora
			this.Name = "Proyecto.Calculadora";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Proyecto.Calculadora.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("CALCULADORA");
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbuttonbox5 = new global::Gtk.VButtonBox ();
			this.vbuttonbox5.Name = "vbuttonbox5";
			this.vbox4.Add (this.vbuttonbox5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbuttonbox5]));
			w2.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbuttonbox3 = new global::Gtk.VButtonBox ();
			this.vbuttonbox3.Name = "vbuttonbox3";
			this.vbox4.Add (this.vbuttonbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbuttonbox3]));
			w3.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox10 = new global::Gtk.VButtonBox ();
			this.vbuttonbox10.Name = "vbuttonbox10";
			this.hbox1.Add (this.vbuttonbox10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox10]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			// Container child button1.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-in", global::Gtk.IconSize.Menu);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Sumar");
			w9.UseUnderline = true;
			w6.Add (w9);
			w5.Add (w6);
			this.button1.Add (w5);
			this.hbox4.Add (this.button1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbuttonbox6 = new global::Gtk.VButtonBox ();
			this.vbuttonbox6.Name = "vbuttonbox6";
			this.hbox4.Add (this.vbuttonbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbuttonbox6]));
			w14.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			// Container child button2.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-zoom-out", global::Gtk.IconSize.Menu);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("Resta");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.button2.Add (w15);
			this.hbox4.Add (this.button2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button2]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.hbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
			w24.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbuttonbox7 = new global::Gtk.VButtonBox ();
			this.vbuttonbox7.Name = "vbuttonbox7";
			this.hbox3.Add (this.vbuttonbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbuttonbox7]));
			w25.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			// Container child button4.Gtk.Container+ContainerChild
			global::Gtk.Alignment w26 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w27 = new global::Gtk.HBox ();
			w27.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_close", global::Gtk.IconSize.Menu);
			w27.Add (w28);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w30 = new global::Gtk.Label ();
			w30.LabelProp = global::Mono.Unix.Catalog.GetString ("Multiplicar");
			w30.UseUnderline = true;
			w27.Add (w30);
			w26.Add (w27);
			this.button4.Add (w26);
			this.hbox3.Add (this.button4);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button4]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbuttonbox8 = new global::Gtk.VButtonBox ();
			this.vbuttonbox8.Name = "vbuttonbox8";
			this.hbox3.Add (this.vbuttonbox8);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbuttonbox8]));
			w35.Position = 2;
			this.hbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
			w36.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			// Container child button5.Gtk.Container+ContainerChild
			global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w38 = new global::Gtk.HBox ();
			w38.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w39 = new global::Gtk.Image ();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-yes", global::Gtk.IconSize.Menu);
			w38.Add (w39);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w41 = new global::Gtk.Label ();
			w41.LabelProp = global::Mono.Unix.Catalog.GetString ("Dividir");
			w41.UseUnderline = true;
			w38.Add (w41);
			w37.Add (w38);
			this.button5.Add (w37);
			this.hbox2.Add (this.button5);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button5]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbuttonbox9 = new global::Gtk.VButtonBox ();
			this.vbuttonbox9.Name = "vbuttonbox9";
			this.hbox2.Add (this.vbuttonbox9);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbuttonbox9]));
			w46.Position = 2;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
			w47.Position = 2;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
			w49.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox ();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbox2.Add (this.vbuttonbox2);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbuttonbox2]));
			w50.Position = 2;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w51.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.vbox3.Add (this.entry1);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry1]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.vbox3.Add (this.entry2);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry2]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbuttonbox4 = new global::Gtk.VButtonBox ();
			this.vbuttonbox4.Name = "vbuttonbox4";
			this.vbox3.Add (this.vbuttonbox4);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbuttonbox4]));
			w54.Position = 2;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w55.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString (" - - -");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbox1.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbuttonbox1]));
			w57.Position = 3;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 416;
			this.DefaultHeight = 300;
			this.Show ();
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
			this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		}
	}
}
